/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.INICIO;

import finaly.AsistenciaEstudiantes;
import interfaz.buscar;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Murillo
 */
public class AsistenciaE extends javax.swing.JFrame {

    /**
     * Creates new form AsistenciaE
     */
    public AsistenciaE() {
        initComponents();
        
    }
    
    buscar bs = new buscar();
//     cedula;
    ArrayList<AsistenciaEstudiantes> arrayAsistenciaES = AsistenciaEstudiantes.arrayAsistenciaEst;
            
    void llenarTabla(String cedula){
        
        try {
//            String cedula = "1314062785";
            
            boolean visualizar = false;
            int fila = 0, cont=0;
            if (AsistenciaEstudiantes.arrayAsistenciaEst.size()==0) {
                JOptionPane.showMessageDialog(this, "Sin datos");
            }else{
                for (int i = 0; i < AsistenciaEstudiantes.arrayAsistenciaEst.size(); i++) {
                    if (AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getCedulaEstudiante().equals(cedula)) {
                        fila++;
                        visualizar=true;
                    }
                } 
                String matriz[][] = new String[fila][4];
                for (int i = 0; i < AsistenciaEstudiantes.arrayAsistenciaEst.size(); i++) {
                    if (AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getCedulaEstudiante().equals(cedula)) {
                        
//                        for(i=0; i<AsistenciaEstudiantes.arrayAsistenciaEst.size(); i++){
                            matriz[cont][0]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getNombreEstudiante();
                            matriz[cont][1]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getApellidoEstudiante();
                            matriz[cont][2]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getFechaAsistencia();
                            matriz[cont][3]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getEstadoAsistencia();
                        cont++;
                    }
                }        
                    if (visualizar==false) {
                    JOptionPane.showMessageDialog(this,"Usuario no encontrado");
                    }
                    tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
                            matriz,
                            new String [] {
                                 "Nombre", "Apellido", "Fecha", "Asistencia", 
                            }
                    ));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsistencia = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        txtCed = new javax.swing.JTextField();
        btMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRES", "APELLIDOS", "FECHAS", "ASISTENCIA"
            }
        ));
        jScrollPane1.setViewportView(tablaAsistencia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 440, 150));

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (5).png"))); // NOI18N
        btSalir.setText("SALIR");
        btSalir.setContentAreaFilled(false);
        btSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));
        jPanel1.add(txtCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 190, -1));

        btMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/london-eye.png"))); // NOI18N
        btMostrar.setText("MOSTRAR");
        btMostrar.setContentAreaFilled(false);
        btMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMostrarMouseClicked(evt);
            }
        });
        jPanel1.add(btMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INTEGRANTES (12).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseClicked
        dispose();
    }//GEN-LAST:event_btSalirMouseClicked

    private void btMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMostrarMouseClicked
        String cedula = txtCed.getText();
        llenarTabla(cedula);
    }//GEN-LAST:event_btMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsistenciaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsistenciaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsistenciaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsistenciaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenciaE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMostrar;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAsistencia;
    public javax.swing.JTextField txtCed;
    // End of variables declaration//GEN-END:variables
}
