/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.INICIO;

import finaly.AsistenciaClass;
import finaly.AsistenciaEstudiantes;
import finaly.Docente;
import finaly.Estudiante;
import finaly.Materia;
import finaly.Semestre;
import finaly.TablaDatos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author 
 */
public class Asistencia extends javax.swing.JFrame {

    
//    DefaultTableModel modelo;
//    String datos [][] = {};
//    String cabeza [] = {"Nombre", "Apellido","Asistencia"};
    
//    TablaDatos tb = new TablaDatos();
    
   
    public void guardarDatos(){
//        int fila = jTable1.getRowCount();
//        int columna = jTable1.getColumnCount();
        JOptionPane.showConfirmDialog(this, "Estudiante: "+jTable1.getValueAt(0, 0));
    }
    
//    ArrayList<Docente> arrayGlobalDocente = Docente.getInstance().getArrayProfesor();
//    ArrayList<Materia> arraGlobalMat = Materia.getInstance().getArrayMateria();
//    ArrayList<Semestre> arraGlobalN = Semestre.getInstance().getArraySemestre();
    ArrayList<Estudiante> arrayEstudiante = Estudiante.arrayEstudiante;
    ArrayList<Semestre> arraySemestre = Semestre.ArraySemestre;
    ArrayList<Materia> arrayMateriA = Materia.arrayMateria;
    ArrayList<Docente> arrayDocente = Docente.arrayProfesor;
    ArrayList<String> arrayIdMateria;
    ArrayList<String> arrayMateriaDoc;
    ArrayList<AsistenciaClass> arrayAsistenciaClass = AsistenciaClass.arrayAsistencia;
    ArrayList<AsistenciaEstudiantes> arrayAsistenciaES = AsistenciaEstudiantes.arrayAsistenciaEst;
    ArrayList<String> arrayEstudianteCed;
    AsistenciaClass objAsisClss = new AsistenciaClass();
    AsistenciaEstudiantes objAsisEs = new AsistenciaEstudiantes();
    boolean valido;
    Calendar fecha = new GregorianCalendar();
    String fechaDeAsistencia = Integer.toString(fecha.get(Calendar.DAY_OF_MONTH))+" / "+Integer.toString(fecha.get(Calendar.MONTH)+1)+" / "+Integer.toString(fecha.get(Calendar.YEAR));
    
    ArrayList<AsistenciaClass> ArrayAsistencia = new ArrayList<>();
    
    /**
     * Creates new form Asistencia
     */
    public Asistencia() {
        initComponents();
        btAsistencia.setEnabled(true);
        txtIDmateria.setEnabled(false);
        jButtonMostrar.setEnabled(false);
        txtCedula.setEnabled(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jComboBoxMaterias = new javax.swing.JComboBox();
        txtIDmateria = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        btAsistencia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRES", "APELLIDOS", "ASISTENCIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 190, 480, 130));

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (5).png"))); // NOI18N
        btSalir.setText("SALIR");
        btSalir.setContentAreaFilled(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 170, -1));

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search (1).png"))); // NOI18N
        btBuscar.setContentAreaFilled(false);
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jPanel1.add(jComboBoxMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 110, -1));
        jPanel1.add(txtIDmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 60, -1));

        jButtonMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/london-eye.png"))); // NOI18N
        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.setContentAreaFilled(false);
        jButtonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMostrarMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        btAsistencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teacher_1.png"))); // NOI18N
        btAsistencia.setText("ASISTENCIA");
        btAsistencia.setContentAreaFilled(false);
        btAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAsistenciaMouseClicked(evt);
            }
        });
        btAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 180, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view.png"))); // NOI18N
        jButton1.setText("MOSTRAR REGISTRO");
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INTEGRANTES (11).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        try {
            String cedula = txtCedula.getText();
            valido=false;
            arrayIdMateria=new ArrayList<>();
            arrayMateriaDoc=new ArrayList<>();
            for (int i = 0; i < Docente.arrayProfesor.size(); i++) {
                if(Docente.arrayProfesor.get(i).getCedula().equals(cedula)){
                    arrayIdMateria.add(Docente.arrayProfesor.get(i).getIdMateria());
                    valido=true;
                }
            }
            if (valido==true) {
                JOptionPane.showConfirmDialog(null, "Existe");
                    for (int i = 0; i < Materia.arrayMateria.size(); i++) {
                        for (int j = 0; j < arrayIdMateria.size(); j++) {
                            if (Materia.arrayMateria.get(i).getIdMateria().equals(arrayIdMateria.get(j))) {
                                arrayMateriaDoc.add("id: "+Materia.arrayMateria.get(i).getIdMateria()+" Name: "+Materia.arrayMateria.get(i).getNombre_Materia());
                                JOptionPane.showConfirmDialog(null, "Existe");
                            }
                        }
                    }

                    for (int i = 0; i < arrayMateriaDoc.size(); i++) {
                        jComboBoxMaterias.addItem(arrayMateriaDoc.get(i));
                    }
                    txtIDmateria.setEnabled(true);
                    jButtonMostrar.setEnabled(true);
            }else{
                JOptionPane.showConfirmDialog(null, "Usuario No encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_btBuscarMouseClicked

    private void jButtonMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarMouseClicked
        
        try {
             String materia = txtIDmateria.getText();
            int level=0;
            arrayEstudianteCed = new ArrayList<>();
            for (int i = 0; i < Materia.arrayMateria.size(); i++) {
                if (Materia.arrayMateria.get(i).getIdMateria().equals(materia)) {
                    level=Integer.parseInt(Materia.arrayMateria.get(i).getIdNivel());
                    JOptionPane.showMessageDialog(null, "materia");
                }
            }

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            Object matriz[] = new Object[3];
            int i;
            for(i=0; i<Estudiante.arrayEstudiante.size(); i++){
                if (Estudiante.arrayEstudiante.get(i).getIdNivel()==level) {
                    arrayEstudianteCed.add(Estudiante.arrayEstudiante.get(i).getCedula());
                    matriz[0]=Estudiante.arrayEstudiante.get(i).getNombre();
                    matriz[1]=Estudiante.arrayEstudiante.get(i).getApellido();
                    matriz[2]=true;
                    JOptionPane.showMessageDialog(null, "Existe");
                    modelo.addRow(matriz);
                }
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
       txtCedula.setEnabled(false);
       txtIDmateria.setEnabled(false);
    }//GEN-LAST:event_jButtonMostrarMouseClicked

    private void btAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAsistenciaMouseClicked
        try {
//            int columna = jTable1.getColumnCount();
            int fila = jTable1.getRowCount();
            objAsisClss.setDocenteAsistencia(txtCedula.getText());
            objAsisClss.setIdAsistencia(Integer.toString(AsistenciaClass.arrayAsistencia.size()));
            objAsisClss.setFechaAsistencia(fechaDeAsistencia);
            objAsisClss.setMateriaAsistencia(txtIDmateria.getText());
            for (int i = 0; i < fila; i++) {
                objAsisEs.setIdAsistenciaE(Integer.toString(AsistenciaClass.arrayAsistencia.size()));
                objAsisEs.setNombreEstudiante((String) jTable1.getValueAt(i, 0));
                objAsisEs.setApellidoEstudiante((String) jTable1.getValueAt(i, 1));
                if ((boolean) jTable1.getValueAt(i, 2)==true) {
                    objAsisEs.setEstadoAsistencia("Asistió"); 
                }else{
                    objAsisEs.setEstadoAsistencia("No Asistió");
                }
                objAsisEs.setCedulaEstudiante(arrayEstudianteCed.get(i));
                objAsisEs.setFechaAsistencia(fechaDeAsistencia);
                objAsisEs.IngresarAsistenciaE();
            }
            System.out.println("");
            objAsisClss.IngresarAsistencia();
            btAsistencia.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
        for (int i = 0; i < AsistenciaEstudiantes.arrayAsistenciaEst.size(); i++) {
            System.out.println("Nombre: "+AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getNombreEstudiante()+" \tCedula: "+AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getCedulaEstudiante()+" \tAsistencia: "+AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getEstadoAsistencia()+" \tFecha: "+AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getFechaAsistencia()+" \tid: "+AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getIdAsistenciaE());
        }
    }//GEN-LAST:event_btAsistenciaMouseClicked

    private void btAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsistenciaActionPerformed
//         int fila = jTable1.getRowCount();
//            objAsisClss.setDocenteAsistencia(null);
//            objAsisClss.setIdAsistencia(Integer.toString(AsistenciaClass.arrayAsistencia.size()));
//            objAsisClss.setDocenteAsistencia(null);
//            objAsisClss.setFechaAsistencia(fechaDeAsistencia);
//            objAsisClss.setMateriaAsistencia(null);
//            for (int i = 0; i < fila; i++) {
//                objAsisEs.setIdAsistenciaE(Integer.toString(AsistenciaClass.arrayAsistencia.size()));
//                objAsisEs.setNombreEstudiante((String) jTable1.getValueAt(i, 0));
//                objAsisEs.setApellidoEstudiante((String) jTable1.getValueAt(i, 1));
//                if ((boolean) jTable1.getValueAt(i, 2)==true) {
//                    objAsisEs.setEstadoAsistencia("Asistió"); 
//                }else{
//                    objAsisEs.setEstadoAsistencia("No Asistió");
//                }
//                objAsisEs.setCedulaEstudiante(arrayEstudianteCed.get(i));
//                objAsisEs.IngresarAsistenciaE();
//            }
//            objAsisClss.IngresarAsistencia();
//            btAsistencia.setEnabled(false);
    }//GEN-LAST:event_btAsistenciaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       listadoAsistencia asiL = new listadoAsistencia();
        asiL.setVisible(true);
        asiL.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAsistencia;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JComboBox jComboBoxMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtIDmateria;
    // End of variables declaration//GEN-END:variables
}
