/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.INICIO;

import finaly.AsistenciaClass;
import finaly.AsistenciaEstudiantes;
import finaly.Docente;
import finaly.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class listadoAsistencia extends javax.swing.JFrame {

    /**
     * Creates new form listadoAsistencia
     */
    public listadoAsistencia() {
        initComponents();
        llenarBox();
    }
    
    void llenarBox(){
        String docente="", materia="";
        for (int i = 0; i < AsistenciaClass.arrayAsistencia.size(); i++) {
            for (int j = 0; j < Docente.arrayProfesor.size(); j++) {
                if (AsistenciaClass.arrayAsistencia.get(i).getDocenteAsistencia().equals(Docente.arrayProfesor.get(j).getCedula())) {
                    docente=Docente.arrayProfesor.get(j).getNombre()+" "+Docente.arrayProfesor.get(j).getApellido();
                }
            }
            for (int j = 0; j < Materia.arrayMateria.size(); j++) {
                if (AsistenciaClass.arrayAsistencia.get(i).getMateriaAsistencia().equals(Materia.arrayMateria.get(j).getIdMateria())) {
                    materia=Materia.arrayMateria.get(j).getNombre_Materia();
                }
            }
               jComboBoxListaA.addItem("[Asistencia +"+AsistenciaClass.arrayAsistencia.get(i).getIdAsistencia()+"] "+ "Fecha: "+AsistenciaClass.arrayAsistencia.get(i).getFechaAsistencia()+" Materia: "+materia+" Docente: "+docente);
        }
    }
    
    ArrayList<Docente> arrayDocente = Docente.arrayProfesor;
    ArrayList<Materia> arrayMateria = Materia.arrayMateria;
    ArrayList<AsistenciaClass> arrayAsistenciaClass = AsistenciaClass.arrayAsistencia;
    ArrayList<AsistenciaEstudiantes> arrayAsistenciaES = AsistenciaEstudiantes.arrayAsistenciaEst;
    
    void llenartabla(int pos){
        try {
            boolean visualizar = false;
            int fila = 0, cont=0;
            if (AsistenciaClass.arrayAsistencia.size()==0) {
                JOptionPane.showMessageDialog(this, "Sin datos");
            }else{
                for (int i = 0; i < AsistenciaEstudiantes.arrayAsistenciaEst.size(); i++) {
                    if (AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getIdAsistenciaE().equals(Integer.toString(pos))) {
                        fila++;
                        visualizar=true;
                    }
                } 
                String matriz[][] = new String[fila][4];
                for (int i = 0; i < AsistenciaEstudiantes.arrayAsistenciaEst.size(); i++) {
                    if (AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getIdAsistenciaE().equals(Integer.toString(pos))) {
                        
                            matriz[cont][0]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getNombreEstudiante();
                            matriz[cont][1]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getApellidoEstudiante();
                            matriz[cont][2]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getFechaAsistencia();
                            matriz[cont][3]=AsistenciaEstudiantes.arrayAsistenciaEst.get(i).getEstadoAsistencia();
                        cont++;
                    }
                }        
                    if (visualizar==false) {
                    JOptionPane.showMessageDialog(this,"Usuario no encontrado");
                    }
                    tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
                            matriz,
                            new String [] {
                                 "Nombre", "Apellido", "Fecha", "Asistencia", 
                            }
                    ));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxListaA = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsistencia = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxListaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListaAActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxListaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 410, -1));

        tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAsistencia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 430, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (5).png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INTEGRANTES (11).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBoxListaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListaAActionPerformed
        int lista = jComboBoxListaA.getSelectedIndex();
        System.out.println(lista);
        llenartabla(lista);
    }//GEN-LAST:event_jComboBoxListaAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listadoAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listadoAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listadoAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listadoAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listadoAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxListaA;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAsistencia;
    // End of variables declaration//GEN-END:variables
}
