/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import finaly.Estudiante;
import finaly.Semestre;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class registroEstudiante extends javax.swing.JFrame {

    Estudiante estud = new Estudiante();
    public static ArrayList<Estudiante> arrayEst= new ArrayList<>();
    ArrayList<Semestre> arraySemestre = Semestre.ArraySemestre;
    
    /**
     * Creates new form ESTUDIANTE
     */
    public registroEstudiante() {
        initComponents();
//        txtIdEstudiante.setText(Integer.toString(Estudiante.arrayEstudiante.size()));
        for (int i = 0; i < Semestre.ArraySemestre.size(); i++) {
               boxNiveles.addItem(Semestre.ArraySemestre.get(i).getNivel()+" "+Semestre.ArraySemestre.get(i).getParalelo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtIdNivel = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        boxNiveles = new javax.swing.JComboBox();
        btRegistrar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        btMostrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 189, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 189, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 189, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 71, -1));

        txtIdNivel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIdNivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdNivel.setEnabled(false);
        jPanel1.add(txtIdNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 55, -1));

        txtCelular.setOpaque(false);
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 177, -1));

        boxNiveles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Niveles" }));
        boxNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNivelesActionPerformed(evt);
            }
        });
        jPanel1.add(boxNiveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 117, -1));

        btRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/register.png"))); // NOI18N
        btRegistrar.setText("REGISTRAR");
        btRegistrar.setContentAreaFilled(false);
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, 40));

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (5).png"))); // NOI18N
        btSalir.setText("SALIR");
        btSalir.setContentAreaFilled(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 120, 40));

        lbError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 338, 279, 23));

        txtEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCivilActionPerformed(evt);
            }
        });
        jPanel1.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 189, -1));

        btMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view.png"))); // NOI18N
        btMostrar.setText("Mostrar");
        btMostrar.setContentAreaFilled(false);
        btMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jLabel6.setText("NOMBRES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, -1));

        lbApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        lbApellido.setText("APELLIDOS");
        jPanel1.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/id-card.png"))); // NOI18N
        jLabel4.setText("CEDULA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/age.png"))); // NOI18N
        jLabel5.setText("EDAD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diamond.png"))); // NOI18N
        jLabel9.setText("ESTADO CIVIL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/laptop (2).png"))); // NOI18N
        jLabel8.setText("ID NIVEL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/phone.png"))); // NOI18N
        jLabel7.setText("TELEFONO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 110, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INTEGRANTES (8).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
      
        try {
            if(txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtCedula.getText().equals("") || txtEdad.getText().equals("") || txtIdNivel.getText().equals("")){
            lbError.setText("## Ingrese datos ##");
            }else{
                estud.setNombre(txtNombre.getText());
                estud.setApellido(txtApellido.getText());
                estud.setCedula(txtCedula.getText());
                estud.setEdad(Integer.parseInt(txtEdad.getText()));
                estud.setIdEstudiante((Estudiante.arrayEstudiante.size()));
                estud.setIdNivel(Integer.parseInt(txtIdNivel.getText()));
                estud.setTelefono(txtCelular.getText());
                estud.IngresarPersona();
    //            arrayEst.add(new Estudiante(estud.getIdEstudiante(), estud.getIdNivel(), estud.getNombre(), estud.getApellido(), estud.getCedula(), estud.getEdad(), estud.getTelefono(), estud.getEstadoCivil()));
                JOptionPane.showMessageDialog(null, "### Datos Guardados ###");
            }
            txtNombre.setText("");
            txtApellido.setText("");
            txtEdad.setText("");
            txtCedula.setText("");
            txtCelular.setText("");
            txtEstadoCivil.setText("");
    //        txtIdEstudiante.setText(Integer.toString(Estudiante.arrayEstudiante.size()));
            txtIdNivel.setText("");
            boxNiveles.setSelectedIndex(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void boxNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNivelesActionPerformed
        if(boxNiveles.getSelectedIndex()>0){
            txtIdNivel.setText(Integer.toString(boxNiveles.getSelectedIndex()-1));
        }
    }//GEN-LAST:event_boxNivelesActionPerformed

    private void btMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarActionPerformed
//        for (int i = 0; i < arrayEst.size(); i++) {
//            JOptionPane.showMessageDialog(null, arrayEst.get(i).getIdNivel()+" "+arrayEst.get(i).getNombre()+" "+arrayEst.get(i).getApellido()+" ");
//        }
        mostrarEstud me = new mostrarEstud();
        me.setVisible(true);
        me.setLocationRelativeTo(null);
    }//GEN-LAST:event_btMostrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCivilActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxNiveles;
    private javax.swing.JButton btMostrar;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btSalir;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbError;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtIdNivel;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
