/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import finaly.Docente;
import finaly.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//import newpackage.docente;


/**
 *
 * @author 
 */
public class registroDocente extends javax.swing.JFrame {
    Docente prof = new Docente();
    public static ArrayList<Docente> arrayProf= new ArrayList<>();
    int i;
    ArrayList<Materia> arrayList = Materia.arrayMateria;
    /**
     * Creates new form PROFESOR
     */
    public registroDocente() {
        initComponents();
        for (int  i = 0; i < Materia.arrayMateria.size(); i++) {
                jComboBoxMaterias.addItem(Materia.arrayMateria.get(i).getNombre_Materia());
            }
//        txtIdDocente.setText(Integer.toString(Docente.arrayProfesor.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btRegistrar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        jComboBoxMaterias = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        txtidMateria = new javax.swing.JTextField();
        btMostrar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jLabel2.setText("NOMBRES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, -1));

        lbApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        lbApellido.setText("APELLIDOS");
        jPanel1.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/id-card.png"))); // NOI18N
        jLabel4.setText("CEDULA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/age.png"))); // NOI18N
        jLabel5.setText("EDAD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 90, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 230, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 230, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/laptop (2).png"))); // NOI18N
        jLabel8.setText("ID MATERIA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 120, 40));

        btRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/register.png"))); // NOI18N
        btRegistrar.setText("REGISTRAR");
        btRegistrar.setContentAreaFilled(false);
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 150, -1));

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (5).png"))); // NOI18N
        btSalir.setText("SALIR");
        btSalir.setContentAreaFilled(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 120, -1));

        lbError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbError.setForeground(new java.awt.Color(255, 0, 0));
        lbError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 342, 23));

        jComboBoxMaterias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Materias" }));
        jComboBoxMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMateriasActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/phone.png"))); // NOI18N
        jLabel7.setText("TELEFONO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 110, 40));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diamond.png"))); // NOI18N
        jLabel9.setText("ESTADO CIVIL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 130, 40));

        txtEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCivilActionPerformed(evt);
            }
        });
        jPanel1.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 150, -1));

        txtidMateria.setEnabled(false);
        jPanel1.add(txtidMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 90, -1));

        btMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view.png"))); // NOI18N
        btMostrar.setText("Mostrar");
        btMostrar.setContentAreaFilled(false);
        btMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 130, -1));

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search (1).png"))); // NOI18N
        btBuscar.setContentAreaFilled(false);
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INTEGRANTES (7).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 477));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
       
        try {
            if(txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtCedula.getText().equals("") || txtEdad.getText().equals("")){
            lbError.setText("## Ingrese datos ##");
            }else{
                prof.setNombre(txtNombre.getText());
                prof.setApellido(txtApellido.getText());
                prof.setCedula((txtCedula.getText()));
                prof.setEdad(Integer.parseInt(txtEdad.getText()));
                prof.setIdDocente(Integer.toString(Docente.arrayProfesor.size()));
                prof.setIdMateria(txtidMateria.getText());
                prof.setTelefono(txtCelular.getText());
                prof.setEstadoCivil(txtEstadoCivil.getText());
               prof.IngresarPersona();
               //arrayProf.add(new Docente(prof.getIdDocente(), prof.getIdMateria(), prof.getNombre(), prof.getApellido(), prof.getCedula(), prof.getEdad(), prof.getTelefono(), prof.getEstadoCivil()));
               JOptionPane.showMessageDialog(null, "### Datos Guardados ###");
                }
            txtNombre.setText("");
            txtApellido.setText("");
            txtCedula.setText("");
            txtEdad.setText("");
            txtEstadoCivil.setText("");
            txtCelular.setText("");
            jComboBoxMaterias.setSelectedIndex(0);
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtEdad.setEnabled(true);
            txtCelular.setEnabled(true);
            txtEstadoCivil.setEnabled(true);
            txtCedula.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
        
//        txtIdDocente.setText(Integer.toString(Docente.arrayProfesor.size()));
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void jComboBoxMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMateriasActionPerformed
        if(jComboBoxMaterias.getSelectedIndex()>0){
            this.txtidMateria.setText(Integer.toString(jComboBoxMaterias.getSelectedIndex()-1));
        }
    }//GEN-LAST:event_jComboBoxMateriasActionPerformed

    private void btMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarActionPerformed
//        for (int i = 0; i < arrayProf.size(); i++) {
//            JOptionPane.showMessageDialog(null, arrayProf.get(i).getNombre()+ " "+ arrayProf.get(i).getApellido());
//        }
        mostrarDoc md = new mostrarDoc();
        md.setVisible(true);
        md.setLocationRelativeTo(null);
    }//GEN-LAST:event_btMostrarActionPerformed

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        try {
            String cedula = txtCedula.getText();
            boolean visualizar = false;
            if (Docente.arrayProfesor.size()==0) {
                JOptionPane.showMessageDialog(this, "Sin datos");
            }else{
                for (int i = 0; i < Docente.arrayProfesor.size(); i++) {
                    if (Docente.arrayProfesor.get(i).getCedula().equals(cedula)) {
                        txtNombre.setText(Docente.arrayProfesor.get(i).getNombre());
                        txtApellido.setText(Docente.arrayProfesor.get(i).getApellido());
                        txtEdad.setText(Integer.toString(Docente.arrayProfesor.get(i).getEdad()));
                        txtCelular.setText(Docente.arrayProfesor.get(i).getTelefono());
                        txtEstadoCivil.setText(Docente.arrayProfesor.get(i).getEstadoCivil());
                        txtNombre.setEnabled(false);
                        txtApellido.setEnabled(false);
                        txtEdad.setEnabled(false);
                        txtCelular.setEnabled(false);
                        txtEstadoCivil.setEnabled(false);
                        txtCedula.setEnabled(false);
                        visualizar=true;
                    }
                }
                if (visualizar==false) {
                    JOptionPane.showMessageDialog(this,"Usuario no encontrado");
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_btBuscarMouseClicked

    private void txtEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCivilActionPerformed

    @Override
    public String toString() {
        return "registroDocente{" + "arrayProf=" + arrayProf + '}';
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btMostrar;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btSalir;
    private javax.swing.JComboBox jComboBoxMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbError;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtidMateria;
    // End of variables declaration//GEN-END:variables
}
