/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import finaly.Estudiante;
import finaly.Materia;
import finaly.Semestre;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//import newpackage.docente;

/**
 *
 * @author 
 */
public class registroMateria extends javax.swing.JFrame {

    ArrayList<Semestre> arraGlobalN = Semestre.ArraySemestre;
    Materia mat = new Materia();
    public static ArrayList<Materia> arrayMate= new ArrayList<>();
    int i;
    /**
     * Creates new form MATERIA
     */
    public registroMateria() {
        initComponents();
//            for ( i = 0; i < arraGlobal.size(); i++) {
//            boxDocente.addItem("id: "+i+" :"+arraGlobal.get(i).getNombre()+" "+arraGlobal.get(i).getApellido());
//            }
            for ( i = 0; i < arraGlobalN.size(); i++) {
                boxNivel.addItem(arraGlobalN.get(i).getNivel()+" "+arraGlobalN.get(i).getParalelo());
            }
//            txtIdMateria.setText(Integer.toString(Materia.arrayMateria.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdNivel = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        boxNivel = new javax.swing.JComboBox();
        btRegistrar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        btMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 153, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/laptop (2).png"))); // NOI18N
        jLabel3.setText("ID NIVEL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 40));

        jLabel5.setBackground(new java.awt.Color(102, 255, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book (1).png"))); // NOI18N
        jLabel5.setText("NOMBRE DE LA MATERIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 270, 29));

        txtIdNivel.setEnabled(false);
        txtIdNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNivelActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 70, -1));

        txtNombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 209, 29));

        boxNivel.setBackground(new java.awt.Color(255, 102, 102));
        boxNivel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        boxNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Niveles" }));
        boxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNivelActionPerformed(evt);
            }
        });
        jPanel1.add(boxNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 140, -1));

        btRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/register.png"))); // NOI18N
        btRegistrar.setText("REGISTRAR");
        btRegistrar.setContentAreaFilled(false);
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 160, 50));

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (5).png"))); // NOI18N
        btSalir.setText("SALIR");
        btSalir.setContentAreaFilled(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 130, -1));
        jPanel1.add(lbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 276, 210, 23));

        btMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view.png"))); // NOI18N
        btMostrar.setText("MOSTRAR");
        btMostrar.setContentAreaFilled(false);
        btMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMostrarMouseClicked(evt);
            }
        });
        btMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INTEGRANTES (9).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 960, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 960, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void boxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNivelActionPerformed
        if(boxNivel.getSelectedIndex()>0){
            this.txtIdNivel.setText(Integer.toString(boxNivel.getSelectedIndex()-1));
        }
    }//GEN-LAST:event_boxNivelActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        try {
            if(txtIdNivel.getText().equals("") || txtNombreMateria.getText().equals("")){
            lbError.setText("## Ingrese datos ##");
            }else{
                mat.setIdNivel(txtIdNivel.getText());
                mat.setIdMateria(Integer.toString(Materia.arrayMateria.size()));
                mat.setNombre_Materia(txtNombreMateria.getText());
               // arrayMate.add(new Materia(mat.getIdMateria(), mat.getNombre_Materia(), mat.getIdNivel()));
                mat.IngresarMateria();
                JOptionPane.showMessageDialog(null, "### Datos Guardados ###");
            }
    //        txtIdMateria.setText(Integer.toString(Materia.arrayMateria.size()));
            txtIdNivel.setText("");
            txtNombreMateria.setText("");
            boxNivel.setSelectedIndex(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMostrarActionPerformed

    private void btMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMostrarMouseClicked
//        for (int i = 0; i < arrayMate.size(); i++) {
//            JOptionPane.showMessageDialog(null, arrayMate.get(i).getIdNivel()+" "+arrayMate.get(i).getNombre_Materia()+" "+arrayMate.get(i).getIdMateria()+" ");
//        }
        mostrarMate mm = new mostrarMate();
        mm.setVisible(true);
        mm.setLocationRelativeTo(null);
    }//GEN-LAST:event_btMostrarMouseClicked

    private void txtNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMateriaActionPerformed

    private void txtIdNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxNivel;
    private javax.swing.JButton btMostrar;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbError;
    private javax.swing.JTextField txtIdNivel;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
